### ISSUE TITLE
Small typo in blueprints.yaml

### ISSUE THREAD

**Issue by bleutzinn** [CPPL/grav-gosquared#2]
Just wanted to let you know that I noticed that in your blueprints.yaml file in the `enabled` field it says:
`hightlight` instead of `highlight`.

**Comment by CraigsOverItAll** [comment]
Thanks for that — fixed it now. Although I probably should have done this in the morning not at 11pm 😁

**Comment by bleutzinn** [comment]
You're welcome. Still broad daylight and sunny over here (.nl) :)
